title: Bill Bunkum
github: https://github.com/billbunkum
stack-over-flow: http://stackoverflow.com/users/6580955/billbunkum 
fb: https://www.facebook.com/williamrichardhurst
linkedin: http://www.linkedin.com/in/billbunkum
twitter: https://twitter.com/billbunkum
blog: http://billbunkum.blogspot.com

home-page: /index.html
about-page: /about.html