url: /favicon.ico
static_files: media/img/favicon.ico
upload: media/img/favicon.ico
app: /app.js

title: Bill Bunkum
github: https://github.com/billbunkum
stack-over-flow: http://stackoverflow.com/users/6580955/billbunkum 
fb: https://www.facebook.com/williamrichardhurst
linkedin: http://www.linkedin.com/in/billbunkum
twitter: https://twitter.com/billbunkum
rando-blog: http://billbunkum.blogspot.com
trello: https://trello.com/billbunkum

dreadlore-image: /dreadlore-shirt.jpg
barkinapp-image: /barkinapp-splash.png
kavakings-img-root: http://kavakings.com/image_main/
trebuchet: https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fputdowntheurinalcake.com%2Fwp-content%2Fuploads%2F2012%2F04%2FTrebuchet.jpg&f=1

home-page: /index.html
about-page: /about.html
bootcamp-blog: /blog.html

contact: /contact.html
formspree-email: https://formspree.io/william.richard.hurst@gmail.com
e-mail: william.richard.hurst@gmail.com

projects-list: /2016/10/18/projectsList.html
obstacles: /2016/11/22/obstacles.html

awesomeinc: https://www.awesomeinc.org/
dev-blog-chalkley: http://blog.teamtreehouse.com/land-a-job-in-development
dev-blog-elsh: https://www.quora.com/How-do-I-transform-myself-from-an-average-programmer-with-a-CS-degree-to-one-of-the-best-programmers-in-ten-years
worthless-blog: http://www.wikihow.com/Get-a-Software-Development-Job
other-worthless-blog: http://www.popsugar.com/tech/How-Get-Web-Developer-Job-23116292

barkinapp-deploy: https://evening-fortress-43547.herokuapp.com/
dotheangle-deploy: 
grocery-deploy: https://grocerybootylist.herokuapp.com/
datbyhate-deploy: https://datebyhate.herokuapp.com/accounts/login/?next=/