#set up file structure and basic site
url: /favicon.ico
include: [_media]
app: /app.js
title: William Hurst Web Developer
#nav links
github: https://github.com/billbunkum
linkedin: https://www.linkedin.com/in/william-hurst-38064937/
twitter: https://twitter.com/3rrible

selected-works-wordpress: https://willhurstartportfolio.wordpress.com/selected-works-art-portfolio
bitbucket: https://bitbucket.org/billbunkum/

#production image path w/o file name: use as {{site.media-prod}}<file-name>
media-prod: https://billbunkum.github.io/_media/
media: _media/

#images: 'splash' used in modal
dreadLore-image: _media/dreadlore_tshirt_transparent.png
dreadLore-splash: _media/dreadLore_screenshot.png
kavakings-splash: _media/kavakings_splash.png
kavakings-image: _media/waveLogo_transparent_blue.png
barkinapp-image: _media/barkinapp-splash.png
dreadlore-image: _media/dreadlore-shirt.jpg

#offsite image links
kavakings-img-root: http://kavakings.com/image_main/

#details links to offsite
dragons-link: http://dnd.wizards.com/
numenera-link:  http://www.numenera.com/
materialize-link: http://materializecss.com/grid.html
flask-tutorial-link: http://flask.pocoo.org/docs/0.12/tutorial/setup/#tutorial-setup
flask-link: http://flask.pocoo.org/

#site map
home-page: /index.html
about-page: /about.html
# bootcamp-blog: /blog.html
contact: /contact.html
formspree-email: https://formspree.io/william.richard.hurst@gmail.com
e-mail: william.richard.hurst@gmail.com

#blog stuffs
projects-list: /2016/10/18/projectsList.html
obstacles: /2016/11/22/obstacles.html
#blog links
# awesomeinc: https://www.awesomeinc.org/
# dev-blog-chalkley: http://blog.teamtreehouse.com/land-a-job-in-development
# dev-blog-elsh: https://www.quora.com/How-do-I-transform-myself-from-an-average-programmer-with-a-CS-degree-to-one-of-the-best-programmers-in-ten-years
# worthless-blog: http://www.wikihow.com/Get-a-Software-Development-Job
# other-worthless-blog: http://www.popsugar.com/tech/How-Get-Web-Developer-Job-23116292

#deploy absolute links
kavakings-deploy: https://kavakings.github.io/
dreadLore-deploy: http://dreadlore.com
barkinapp-deploy: https://evening-fortress-43547.herokuapp.com/
dotheangle-deploy: https://billbunkum.github.io/do-the-angle/
grocery-deploy: https://grocerybootylist.herokuapp.com/
datebyhate-deploy: https://datebyhate.herokuapp.com/accounts/login/?next=/
click-rage-deploy: https://click-rage.herokuapp.com/

#more blog links
blog-2017-01-11-scrum: https://en.wikipedia.org/wiki/Scrum_(software_development)
blog-2017-01-11-SAFe: https://en.wikipedia.org/wiki/Scaled_Agile_Framework
blog-2017-01-11-extreme: https://en.wikipedia.org/wiki/Extreme_Programming
blog-2017-01-11-ivyLee: http://jamesclear.com/ivy-lee

#2017-03-28 links
mongodb: https://docs.mongodb.com/manual/installation/
mongoosejs: http://mongoosejs.com/
expressjs: http://expressjs.com/
chris-sevilleja: https://scotch.io/bar-talk/expressjs-4-0-new-features-and-upgrading-from-3-0
express-generator: http://expressjs.com/en/starter/generator.html
thinkster: https://thinkster.io/tutorials/mean-stack
kendrick-coleman: https://www.airpair.com/javascript/complete-expressjs-nodejs-mongodb-crud-skeleton

#2017-04-21 links
noSQL: https://www.mongodb.com/document-databases
thinkster-nodeJS: https://thinkster.io/tutorials/design-a-robust-json-api/getting-and-setting-user-data
stackExchange: http://stackoverflow.com/questions/43332178/why-use-delete-post-instead-of-put-for-unfollowing-following-a-user/43332503#43332503