url: /favicon.ico
static_files: media/img/favicon.ico
upload: media/img/favicon.ico

title: Bill Bunkum
github: https://github.com/billbunkum
stack-over-flow: http://stackoverflow.com/users/6580955/billbunkum 
fb: https://www.facebook.com/williamrichardhurst
linkedin: http://www.linkedin.com/in/billbunkum
twitter: https://twitter.com/billbunkum
rando-blog: http://billbunkum.blogspot.com

dreadlore-image: /dreadlore-shirt.jpg

home-page: /index.html
about-page: /about.html
bootcamp-blog: /blog.html

contact: /contact.html
formspree-email: https://formspree.io/william.richard.hurst@gmail.com
e-mail: william.richard.hurst@gmail.com

projects-list: /2016/10/18/projectsList.html
obstacles: /2016/11/22/obstacles.html

awesomeinc: https://www.awesomeinc.org/